<?xml version="1.0" encoding="utf-8"?><Database Name="trackyourtasksdb" Class="TrackYourTasksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=D:\Development\Projects\trackyourtasks.net\src\trackyourtasks.net\App_Data\trackyourtasksdb.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="Trackyourtasks.Core.Properties.Settings" SettingsPropertyName="trackyourtasksdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" AutoSync="OnInsert" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SecretPhrase" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" AccessModifier="Protected" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="ActualWork" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="Timestamp" AccessModifier="Protected" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" UpdateCheck="Always" IsVersion="true" />
    </Type>
  </Table>
</Database>